#!/bin/sh                                                                                                                                                  
npx prettier --write .                                                                                                                                     
git add .   